/**
 * Commodore 64 color palette.
 *
 * The C64 (1982) featured a fixed 16-color palette generated by the
 * VIC-II chip. The colors have a distinctive warm, slightly muted
 * appearance that gives C64 games their recognizable look.
 *
 * @category Palettes
 * @module palettes/commodore64
 * @since 0.5.0
 *
 * @see {@link https://www.c64-wiki.com/wiki/Color} C64 Wiki
 */

import type { HexColor, NamedColorPalette } from './types';

/**
 * Named colors for the Commodore 64 palette.
 *
 * @since 0.5.0
 */
export interface C64Colors {
  BLACK: HexColor;
  WHITE: HexColor;
  RED: HexColor;
  CYAN: HexColor;
  PURPLE: HexColor;
  GREEN: HexColor;
  BLUE: HexColor;
  YELLOW: HexColor;
  ORANGE: HexColor;
  BROWN: HexColor;
  LIGHT_RED: HexColor;
  DARK_GRAY: HexColor;
  GRAY: HexColor;
  LIGHT_GREEN: HexColor;
  LIGHT_BLUE: HexColor;
  LIGHT_GRAY: HexColor;
}

/**
 * Commodore 64 16-color palette.
 *
 * Uses the widely-accepted "Pepto" palette values, which accurately
 * represent the colors as displayed on period-correct monitors.
 *
 * @since 0.5.0
 *
 * @example
 * ```ts
 * // Classic C64 blue screen
 * ctx.fillRect(0, 0, 320, 200, C64.named.BLUE);
 * ctx.fillRect(10, 10, 300, 180, C64.named.LIGHT_BLUE);
 *
 * // Text in light blue on blue (iconic C64 look)
 * ctx.drawText('READY.', 10, 10, C64.named.LIGHT_BLUE);
 * ```
 */
export const C64: NamedColorPalette<C64Colors> = {
  name: 'Commodore 64',
  colors: [
    '#000000', // 0  - Black
    '#FFFFFF', // 1  - White
    '#880000', // 2  - Red
    '#AAFFEE', // 3  - Cyan
    '#CC44CC', // 4  - Purple
    '#00CC55', // 5  - Green
    '#0000AA', // 6  - Blue
    '#EEEE77', // 7  - Yellow
    '#DD8855', // 8  - Orange
    '#664400', // 9  - Brown
    '#FF7777', // 10 - Light Red
    '#333333', // 11 - Dark Gray
    '#777777', // 12 - Gray
    '#AAFF66', // 13 - Light Green
    '#0088FF', // 14 - Light Blue
    '#BBBBBB', // 15 - Light Gray
  ] as const,
  named: {
    BLACK: '#000000',
    WHITE: '#FFFFFF',
    RED: '#880000',
    CYAN: '#AAFFEE',
    PURPLE: '#CC44CC',
    GREEN: '#00CC55',
    BLUE: '#0000AA',
    YELLOW: '#EEEE77',
    ORANGE: '#DD8855',
    BROWN: '#664400',
    LIGHT_RED: '#FF7777',
    DARK_GRAY: '#333333',
    GRAY: '#777777',
    LIGHT_GREEN: '#AAFF66',
    LIGHT_BLUE: '#0088FF',
    LIGHT_GRAY: '#BBBBBB',
  },
} as const;
